[build]
  command = ""  # No build command needed for static HTML
  publish = "/"  # Set the root folder as the publish directory

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
