backend:
  name: git-gateway
  branch: main # Change if your default branch is different

media_folder: "images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Site Content"
    format: "json"
    extension: "json"
    identifier_field: "title"
    files:
      - label: "Homepage Content"
        name: "homepage"
        file: "content.json"
        fields:
          - { label: "Title", name: "title", widget: "string" } 
          - { label: "Works", name: "works", widget: "string" }
          - { label: "About", name: "about", widget: "string" }
          - { label: "Garden", name: "garden", widget: "string" }
          - { label: "Shop", name: "shop", widget: "string" }
          - { label: "Contact", name: "contact", widget: "string" }
